#!/usr/bin/env bash
# curl, xmlstarlet, timg used as examples
declare -a dependencies=("curl" "xmlstarlet" "timg")
# Function to check if a dependency is installed and install it if not
check_and_install() {
    local dependency=$1
    if ! brew list --formula | grep -qw "$dependency"; then
        echo -e "$dependency is not installed. Installing..."
        brew install "$dependency"
    else
        echo -e "$dependency is already installed."
    fi
}
# Ensure Homebrew is installed
if ! command -v brew &> /dev/null; then
    echo -e "Homebrew is not installed. Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
# Check and install each dependency
for dependency in "${dependencies[@]}"; do
    check_and_install "$dependency"
    if ! command -v "$dependency" &> /dev/null; then
        echo -e "Error: $dependency is required but could not be installed."
        exit 1
    fi
done
echo -e "All dependencies are installed." 
